{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    {{- include "ovad.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretValues }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
